### ISSUE TITLE
Potentially a duplicate?

### ISSUE THREAD

**Issue by birbjam** [BNHM/AmphibiaWebDiseasePortalAPI#2]
Both

https://github.com/BNHM/AmphibiaWebDiseasePortalAPI/blob/master/data/yearCollected_diseaseDetected_Bsal.json

and 

https://github.com/BNHM/AmphibiaWebDiseasePortalAPI/blob/master/data/yearCollected_Bsal.json

display identical values with no positive results? 
having no bsal found over all the years it was collected just seems like that's wrong?

**Comment by mkoo** [comment]
Yes that is correct in terms of no positive Bsal found yet because we only
have US data so far-- it's a potentially devastating wildlife disease we
want to keep it that way in the US. We can reach out beyond the US once we
have this portal up and ready for the public since positives know from
there and Asia.

**Comment by birbjam** [comment]
Oh gotcha.
